name = "MC Eternal (Hysteria version)"
author = "gary"
version = "1.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c021b48b09f0340406b41bed077c1efe08b6387e1dc2ca41afec2c16982fc540"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
