name = "MC Eternal (Hysteria version)"
author = "gary"
version = "1.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c50842b249a56923bfe974c3f445b242c45417596bfdc20350640cd1e1b1c227"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
