name = "MC Eternal (Hysteria version)"
author = "gary"
version = "1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0aba4803dead343663c2e605bf451a8bacb105550412143b0db485e40289449d"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
