name = "MC Eternal (Hysteria version)"
author = "gary"
version = "1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0571cc01f576c59bc7560ea266bb3677dc923d65a9b2ce440834c54c1fba186"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
