name = "MC Eternal (Hysteria version)"
author = "gary"
version = "1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "78271bc3b46a5cd5017e8a05ae04db80d61ffa674fa7e9a9a81c405aa75c27b5"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
