name = "MC Eternal (Hysteria version)"
author = "gary"
version = "1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc37eadeb497e2e526519b8263f30535750de4d78561c9297d3be8d7aec197de"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
